export const allBlueprints = [
  {
    name: "Blue Print One",
    default: true,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 2",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 3",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 4",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 5",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 6",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 7",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 8",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 9",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 10",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
  {
    name: "Blue Print 11",
    default: false,
    tags: [
      { title: "Alpha", id: "1", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Beta", id: "2", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Gamma", id: "3", textColor: "#EC6F6F", bgColor: "#FFC4C4" },
      { title: "Delta", id: "4", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Epsilon", id: "5", textColor: "#707CCC", bgColor: "#AFB6E5" },
      { title: "Zeta", id: "6", textColor: "#E5699A", bgColor: "#F4ACC8" },
      { title: "Eta", id: "7", textColor: "#1AA9BE", bgColor: "#4CD9ED" },
      { title: "Theta", id: "8", textColor: "#EDBB63", bgColor: "#FFEDCD" },
      { title: "Iota", id: "9", textColor: "#3784E8", bgColor: "#80B7FF" },
      { title: "Kappa", id: "10", textColor: "#CAA452", bgColor: "#FFE2A4" },
      { title: "Lambda", id: "11", textColor: "#6C90B4", bgColor: "#CCE6FF" },
      { title: "Mu", id: "12", textColor: "#707CCC", bgColor: "#AFB6E5" },
    ],
  },
];
