export const allPlugins = [
  {
    id: 1,
    selected: true,
    fallbackIcon: "A",
    bgColor: "#CCE6FF",
    textColor: "#6C90B4",
  },
  {
    id: 2,
    selected: true,
    fallbackIcon: "B",
    bgColor: "#FFE2A4",
    textColor: "#CAA452",
  },
  {
    id: 3,
    selected: false,
    fallbackIcon: "C",
    bgColor: "#FFC4C4",
    textColor: "#EC6F6F",
  },
  {
    id: 4,
    selected: false,
    fallbackIcon: "D",
    bgColor: "#80B7FF",
    textColor: "#3784E8",
  },
  {
    id: 5,
    selected: false,
    fallbackIcon: "E",
    bgColor: "#AFB6E5",
    textColor: "#707CCC",
  },
  {
    id: 6,
    selected: false,
    fallbackIcon: "F",
    bgColor: "#F4ACC8",
    textColor: "#E5699A",
  },
  {
    id: 7,
    selected: true,
    fallbackIcon: "G",
    bgColor: "#4CD9ED",
    textColor: "#1AA9BE",
  },
  {
    id: 8,
    selected: false,
    fallbackIcon: "H",
    bgColor: "#FFEDCD",
    textColor: "#EDBB63",
  },
  {
    id: 9,
    selected: false,
    fallbackIcon: "I",
    bgColor: "#CCE6FF",
    textColor: "#6C90B4",
  },
  {
    id: 10,
    selected: false,
    fallbackIcon: "J",
    bgColor: "#FFC4C4",
    textColor: "#EC6F6F",
  },
  {
    id: 11,
    selected: false,
    fallbackIcon: "K",
    bgColor: "#80B7FF",
    textColor: "#3784E8",
  },
  {
    id: 12,
    selected: false,
    fallbackIcon: "L",
    bgColor: "#AFB6E5",
    textColor: "#707CCC",
  },
  {
    id: 13,
    selected: false,
    fallbackIcon: "M",
    bgColor: "#F4ACC8",
    textColor: "#E5699A",
  },
  {
    id: 14,
    selected: false,
    fallbackIcon: "N",
    bgColor: "#4CD9ED",
    textColor: "#1AA9BE",
  },
  {
    id: 15,
    selected: false,
    fallbackIcon: "O",
    bgColor: "#FFEDCD",
    textColor: "#EDBB63",
  },
  {
    id: 16,
    selected: false,
    fallbackIcon: "P",
    bgColor: "#CCE6FF",
    textColor: "#6C90B4",
  },
  {
    id: 17,
    selected: false,
    fallbackIcon: "Q",
    bgColor: "#AFB6E5",
    textColor: "#707CCC",
  },
  {
    id: 18,
    selected: false,
    fallbackIcon: "R",
    bgColor: "#80B7FF",
    textColor: "#3784E8",
  },
  {
    id: 19,
    selected: false,
    fallbackIcon: "S",
    bgColor: "#FFC4C4",
    textColor: "#EC6F6F",
  },
  {
    id: 20,
    selected: false,
    fallbackIcon: "T",
    bgColor: "#4CD9ED",
    textColor: "#1AA9BE",
  },
];
